edmonton_map/edmonton_map/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('render/', include('render.urls')),
]

edmonton_map/render/urls.py
from django.urls import path

from . import views

app_name = "render"
urlpatterns = [
    path("", views.index, name="index"),
    path('cesium_token', views.cesium_token, name='cesium_token'),
]

edmonton_map/render/models.py
from django.db import models

# Create your models here.

edmonton_map/render/views.py
from django.http import HttpResponse
import os
from django.shortcuts import render

# Create your views here.
def index(request):
    CESIUM_API_KEY = os.getenv("CESIUM_API_KEY")
    return render(request, "render/index.html", {"CESIUM_API_KEY": CESIUM_API_KEY})

def cesium_token(request):
    CESIUM_API_KEY = os.getenv("CESIUM_API_KEY") or ''
    return HttpResponse(CESIUM_API_KEY.encode(), content_type="text/plain")

edmonton_map/render/templates/render/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <!-- Include the CesiumJS JavaScript and CSS files -->
    <script src="https://cesium.com/downloads/cesiumjs/releases/1.129/Build/Cesium/Cesium.js"></script>
    <link href="https://cesium.com/downloads/cesiumjs/releases/1.129/Build/Cesium/Widgets/widgets.css" rel="stylesheet">
</head>

<body>
    <div id="cesiumContainer"></div>
    <script type="module">
        async function createCesiumViewer() {
            // Your access token can be found at: https://ion.cesium.com/tokens.
            // Replace `your_access_token` with your Cesium ion access token.
            const cesium_token = await fetch("{% url 'render:cesium_token' %}").then(response => response.text());
            Cesium.Ion.defaultAccessToken = cesium_token;
            Cesium.ArcGisMapService.defaultAccessToken = cesium_token;

            const viewer = new Cesium.Viewer("cesiumContainer", {
                timeline: false,
                animation: false,
                sceneModePicker: false,
                baseLayerPicker: false,
                geocoder: Cesium.IonGeocodeProviderType.GOOGLE,
                // The globe does not need to be displayed,
                // since the Photorealistic 3D Tiles include terrain
                globe: false,
            });

            // Enable rendering the sky
            viewer.scene.skyAtmosphere.show = true;

            // Add Photorealistic 3D Tiles
            try {
                const tileset = await Cesium.createGooglePhotorealistic3DTileset({
                    // Only the Google Geocoder can be used with Google Photorealistic 3D Tiles.  Set the `geocode` property of the viewer constructor options to IonGeocodeProviderType.GOOGLE.
                    onlyUsingWithGoogleGeocoder: true,
                });
                viewer.scene.primitives.add(tileset);
            } catch (error) {
                console.log(`Error loading Photorealistic 3D Tiles tileset.
  ${error}`);
            }

            viewer.scene.camera.setView({
                destination: Cesium.Cartesian3.fromDegrees(-113.4937, 53.5461, 400),
                orientation: new Cesium.HeadingPitchRoll(
                    4.6550106925119925,
                    -0.2863894863138836,
                    1.3561760425773173e-7,
                ),
            });

            // // Fly the camera to San Francisco at the given longitude, latitude, and height.
            // viewer.camera.flyTo({
            //     destination:
            //     orientation: {
            //         heading: Cesium.Math.toRadians(0.0),
            //         pitch: Cesium.Math.toRadians(-15.0),
            //     }
            // });
        }

        createCesiumViewer();
    </script>
    </div>
</body>

</html>